Repository prgrms-be-devcourse/NBE5-6-3-Team05, pull requests merged in 2025-06, with the labels that each got.

#3 Kdg
  src/main/java/com/grepp/moodlink/app/controller/web/recommend/RecommendController.java
  src/main/java/com/grepp/moodlink/app/model/data/book/BookRepository.java
  src/main/java/com/grepp/moodlink/app/model/data/music/MusicService.java
  src/main/java/com/grepp/moodlink/app/model/keyword/KeywordRepository.java
  src/main/java/com/grepp/moodlink/app/model/llm/LlmService.java
  src/main/java/com/grepp/moodlink/app/model/llm/RecommendationService.java
  src/main/java/com/grepp/moodlink/app/model/member/MemberService.java
  src/main/java/com/grepp/moodlink/app/model/member/entity/Member.java
  src/main/java/com/grepp/moodlink/infra/error/UserNotFoundException.java
  src/main/java/com/grepp/moodlink/infra/response/ResponseCode.java
  src/test/java/com/grepp/moodlink/app/model/data/music/MusicServiceTest.java
Labels: 🔧 enhancement, 🛠 backend

#5 Lkh - 회원가입, 로그인 디자인 & 이슈 해결
  README.md
  pom.xml
  src/main/java/com/grepp/moodlink/app/controller/web/auth/AuthController.java
  src/main/java/com/grepp/moodlink/app/controller/web/auth/payload/SigninRequest.java
  src/main/java/com/grepp/moodlink/app/controller/web/auth/payload/SignupRequest.java
  src/main/java/com/grepp/moodlink/app/controller/web/home/HomeController.java
  src/main/java/com/grepp/moodlink/app/model/auth/token/RefreshTokenRepository.java
  src/main/java/com/grepp/moodlink/app/model/auth/token/RefreshTokenService.java
  src/main/java/com/grepp/moodlink/app/model/auth/token/UserBlackListRepository.java
  src/main/java/com/grepp/moodlink/app/model/auth/token/dto/AccessTokenDto.java
  src/main/java/com/grepp/moodlink/app/model/auth/token/dto/TokenDto.java
  src/main/java/com/grepp/moodlink/app/model/auth/token/entity/RefreshToken.java
  src/main/java/com/grepp/moodlink/app/model/auth/token/entity/UserBlackList.java
  src/main/java/com/grepp/moodlink/app/model/data/music/MusicRepositoryCustom.java
  src/main/java/com/grepp/moodlink/app/model/data/music/MusicRepositoryImpl.java
  src/main/java/com/grepp/moodlink/app/model/home/HomeService.java
  src/main/java/com/grepp/moodlink/app/model/keyword/entity/KeywordSelection.java
  src/main/java/com/grepp/moodlink/app/model/member/MemberService.java
  src/main/java/com/grepp/moodlink/app/model/member/dto/MemberDto.java
  src/main/java/com/grepp/moodlink/app/model/member/entity/Member.java
  src/main/java/com/grepp/moodlink/infra/auth/UserDetailsServiceImpl.java
  src/main/java/com/grepp/moodlink/infra/auth/token/JwtAuthenticationEntryPoint.java
  src/main/java/com/grepp/moodlink/infra/auth/token/JwtProvider.java
  src/main/java/com/grepp/moodlink/infra/auth/token/TokenCookieFactory.java
  src/main/java/com/grepp/moodlink/infra/auth/token/code/GrantType.java
  src/main/java/com/grepp/moodlink/infra/auth/token/code/TokenType.java
  src/main/java/com/grepp/moodlink/infra/auth/token/filter/AuthExceptionFilter.java
  src/main/java/com/grepp/moodlink/infra/auth/token/filter/JwtAuthenticationFilter.java
  src/main/java/com/grepp/moodlink/infra/auth/token/filter/LogoutFilter.java
  src/main/java/com/grepp/moodlink/infra/error/exceptions/AuthApiException.java
  src/main/java/com/grepp/moodlink/infra/error/exceptions/AuthWebException.java
  src/main/java/com/grepp/moodlink/infra/error/exceptions/CommonException.java
  src/main/java/com/grepp/moodlink/infra/response/ResponseCode.java
  src/main/resources/application.properties
  src/main/resources/templates/auth/signin.html
  src/main/resources/templates/auth/signup.html
  src/main/resources/templates/home/search.html
Labels: ♻️ refactor, 🎨 style, 🔧 enhancement, 🚧 in progress, 🛠 backend

#8 Kdg
  src/main/java/com/grepp/moodlink/app/controller/web/recommend/RecommendController.java
  src/main/java/com/grepp/moodlink/app/model/data/book/dto/BookDto.java
  src/main/java/com/grepp/moodlink/app/model/llm/LlmService.java
  src/main/java/com/grepp/moodlink/app/model/result/dto/BookSimpleDto.java
  src/main/java/com/grepp/moodlink/app/model/result/dto/MovieSimpleDto.java
  src/main/java/com/grepp/moodlink/app/model/result/dto/SongSimpleDto.java
  src/main/java/com/grepp/moodlink/infra/error/LLMResourceException.java
  src/main/java/com/grepp/moodlink/infra/response/ResponseCode.java
  src/main/resources/templates/result/result.html
Labels: ♻️ refactor, ✨ feature, 🎨 frontend

#12 (fix) 검색 이슈 해결
  src/main/java/com/grepp/moodlink/app/model/data/book/dto/BookDto.java
Labels: 💧 순한맛, ✅ done, 🐛bug, 🛠 backend

#13 Kdg
  src/main/java/com/grepp/moodlink/app/controller/web/home/HomeController.java
  src/main/java/com/grepp/moodlink/app/model/keyword/KeywordService.java
  src/main/java/com/grepp/moodlink/app/model/llm/RecommendationRepository.java
  src/main/java/com/grepp/moodlink/app/model/llm/RecommendationService.java
  src/main/java/com/grepp/moodlink/app/model/llm/code/RecommendContentType.java
  src/main/resources/templates/.DS_Store
  src/main/resources/templates/auth/signin.html
  src/main/resources/templates/fragments.html
  src/main/resources/templates/home/mainPage.html
  src/main/resources/templates/home/search.html
  src/main/resources/templates/layout.html
  src/main/resources/templates/recommend/recommend.html
  src/main/resources/templates/result/result.html
  src/main/resources/templates/users/like.html
  src/main/resources/templates/users/modify.html
  src/main/resources/templates/users/mypage.html
  src/main/resources/templates/worldcup/worldcup.html
  src/test/java/com/grepp/moodlink/app/model/llm/RecommendationServiceTest.java
Labels: ✨ feature, 🎨 frontend, 🛠 backend

#16 Ajh
  src/main/java/com/grepp/moodlink/app/controller/api/book/BookApiController.java
  src/main/java/com/grepp/moodlink/app/controller/api/movie/MovieApiController.java
  src/main/java/com/grepp/moodlink/app/controller/api/music/MusicApiController.java
  src/main/java/com/grepp/moodlink/app/controller/api/worldcup/payload/WorldcupIdsRequest.java
  src/main/java/com/grepp/moodlink/app/model/data/book/BookRepository.java
  src/main/java/com/grepp/moodlink/app/model/data/book/BookService.java
  src/main/java/com/grepp/moodlink/app/model/data/movie/MovieService.java
  src/main/java/com/grepp/moodlink/app/model/data/movie/dto/MovieWorldcupDto.java
  src/main/java/com/grepp/moodlink/app/model/data/music/MusicService.java
  src/main/java/com/grepp/moodlink/app/model/data/music/dto/MusicWorldcupDto.java
  src/main/java/com/grepp/moodlink/app/model/worldcup/WorldcupService.java
  src/main/java/com/grepp/moodlink/app/model/worldcup/entity/Worldcup.java
  src/main/resources/templates/worldcup/create.html
  src/main/resources/templates/worldcup/play.html
  src/main/resources/templates/worldcup/result.html
  src/main/resources/templates/worldcup/worldcup.html
Labels: ✨ feature, 🎨 frontend, 🛠 backend

#27 Kdg
  moodlink/src/main/resources/templates/fragments.html
Labels: 🧑‍🎨 design

#30 Lkh - 검색 페이지 이슈 해결
  moodlink/src/main/java/com/grepp/moodlink/app/model/data/book/dto/BookDto.java
  moodlink/src/main/java/com/grepp/moodlink/app/model/data/movie/dto/MovieDto.java
  moodlink/src/main/java/com/grepp/moodlink/app/model/data/music/dto/MusicDto.java
  moodlink/src/main/java/com/grepp/moodlink/app/model/home/SearchService.java
  moodlink/src/main/java/com/grepp/moodlink/infra/config/SecurityConfig.java
  moodlink/src/main/resources/templates/fragments.html
  moodlink/src/main/resources/templates/home/search.html
Labels: 🎨 frontend

#31 Kms - 회원가입 controller 메소드 return 값 redirect로 수정
  moodlink/src/main/java/com/grepp/moodlink/app/controller/web/auth/WebAuthController.java
Labels: ♻️ refactor, 🐛bug, 🛠 backend

#37 (fix) - 음악 검색 이미지 크기 수정
  moodlink/src/main/resources/templates/fragments.html
  moodlink/src/main/resources/templates/home/search.html
Labels: 🎨 frontend

#41 Kms - 검색 결과 html 수정
  moodlink/src/main/resources/templates/home/search.html
Labels: 🎨 frontend, 🎨 style, 🔧 enhancement, 🧑‍🎨 design
